# Generated by Django 5.0.7 on 2024-09-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_status_alter_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='view',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
