# Generated by Django 5.0.7 on 2024-09-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_room_amenities_room_bed_type_room_size_room_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='amenities',
            field=models.TextField(blank=True, help_text='List of amenities separated by commas'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Double', 'Double'), ('Queen', 'Queen'), ('King', 'King')], max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to='rooms/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.IntegerField(blank=True, help_text='Size of the room in square meters', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='view',
            field=models.CharField(blank=True, choices=[('Sea', 'Sea'), ('Mountain', 'Mountain'), ('City', 'City')], max_length=100),
        ),
    ]
